import { apiAction } from '../api/utils';
import * as api from '../api/bike';

export const PERSIST_BIKE_START = 'BIKE/PERSIST_BIKE_START';
export const PERSIST_BIKE_SUCCESS = 'BIKE/PERSIST_BIKE_SUCCESS';
export const PERSIST_BIKE_ERROR = 'BIKE/PERSIST_BIKE_ERROR';

export const DELETE_BIKE_START = 'BIKE/DELETE_BIKE_START';
export const DELETE_BIKE_SUCCESS = 'BIKE/DELETE_BIKE_SUCCESS';
export const DELETE_BIKE_ERROR = 'BIKE/DELETE_BIKE_ERROR';

export const FETCH_BIKES_START = 'BIKE/FETCH_BIKES_START';
export const FETCH_BIKES_SUCCESS = 'BIKE/FETCH_BIKES_SUCCESS';
export const FETCH_BIKES_ERROR = 'BIKE/FETCH_BIKES_ERROR';

export const CREATE_BIKE_BOOKING_START = 'BIKE/CREATE_BIKE_BOOKING_START';
export const CREATE_BIKE_BOOKING_SUCCESS = 'BIKE/CREATE_BIKE_BOOKING_SUCCESS';
export const CREATE_BIKE_BOOKING_ERROR = 'BIKE/CREATE_BIKE_BOOKING_ERROR';

export const DELETE_BIKE_BOOKING_START = 'BIKE/DELETE_BIKE_BOOKING_START';
export const DELETE_BIKE_BOOKING_SUCCESS = 'BIKE/DELETE_BIKE_BOOKING_SUCCESS';
export const DELETE_BIKE_BOOKING_ERROR = 'BIKE/DELETE_BIKE_BOOKING_ERROR';

export const persistBike = apiAction(api.persistBike, PERSIST_BIKE_START, PERSIST_BIKE_SUCCESS, PERSIST_BIKE_ERROR);
export const fetchBikes = apiAction(api.fetchBikes, FETCH_BIKES_START, FETCH_BIKES_SUCCESS, FETCH_BIKES_ERROR);
export const deleteBike = apiAction(api.deleteBike, DELETE_BIKE_START, DELETE_BIKE_SUCCESS, DELETE_BIKE_ERROR);
export const bookBike = apiAction(api.bookBike, CREATE_BIKE_BOOKING_START, CREATE_BIKE_BOOKING_SUCCESS, CREATE_BIKE_BOOKING_ERROR);
export const deleteBikeBooking = apiAction(api.deleteBikeBooking, DELETE_BIKE_BOOKING_START, DELETE_BIKE_BOOKING_SUCCESS, DELETE_BIKE_BOOKING_ERROR);
